package com.xing.manage.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig checkNowDaoConfig;
    private final DaoConfig resourceDaoConfig;

    private final CheckNowDao checkNowDao;
    private final ResourceDao resourceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        checkNowDaoConfig = daoConfigMap.get(CheckNowDao.class).clone();
        checkNowDaoConfig.initIdentityScope(type);

        resourceDaoConfig = daoConfigMap.get(ResourceDao.class).clone();
        resourceDaoConfig.initIdentityScope(type);

        checkNowDao = new CheckNowDao(checkNowDaoConfig, this);
        resourceDao = new ResourceDao(resourceDaoConfig, this);

        registerDao(CheckNow.class, checkNowDao);
        registerDao(Resource.class, resourceDao);
    }
    
    public void clear() {
        checkNowDaoConfig.clearIdentityScope();
        resourceDaoConfig.clearIdentityScope();
    }

    public CheckNowDao getCheckNowDao() {
        return checkNowDao;
    }

    public ResourceDao getResourceDao() {
        return resourceDao;
    }

}
