package com.xing.module.quality.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xing.module.quality.bean.PlanMonth;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PlanMonth".
*/
public class PlanMonthDao extends AbstractDao<PlanMonth, Long> {

    public static final String TABLENAME = "PlanMonth";

    /**
     * Properties of entity PlanMonth.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Month = new Property(1, String.class, "month", false, "MONTH");
        public final static Property PlanCount = new Property(2, int.class, "planCount", false, "PLAN_COUNT");
    }

    private DaoSession daoSession;


    public PlanMonthDao(DaoConfig config) {
        super(config);
    }
    
    public PlanMonthDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PlanMonth\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MONTH\" TEXT NOT NULL ," + // 1: month
                "\"PLAN_COUNT\" INTEGER NOT NULL );"); // 2: planCount
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PlanMonth\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PlanMonth entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getMonth());
        stmt.bindLong(3, entity.getPlanCount());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PlanMonth entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getMonth());
        stmt.bindLong(3, entity.getPlanCount());
    }

    @Override
    protected final void attachEntity(PlanMonth entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PlanMonth readEntity(Cursor cursor, int offset) {
        PlanMonth entity = new PlanMonth( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // month
            cursor.getInt(offset + 2) // planCount
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PlanMonth entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMonth(cursor.getString(offset + 1));
        entity.setPlanCount(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PlanMonth entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PlanMonth entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PlanMonth entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
