package com.xing.manage.db;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.xing.manage.bean.device.Record;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECORD".
*/
public class RecordDao extends AbstractDao<Record, Long> {

    public static final String TABLENAME = "RECORD";

    /**
     * Properties of entity Record.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Mmid = new Property(0, Long.class, "mmid", true, "_id");
        public final static Property Id = new Property(1, Long.class, "id", false, "ID");
        public final static Property StartTime = new Property(2, String.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(3, String.class, "endTime", false, "END_TIME");
        public final static Property Checker = new Property(4, String.class, "checker", false, "CHECKER");
        public final static Property Type = new Property(5, String.class, "type", false, "TYPE");
        public final static Property Value = new Property(6, String.class, "value", false, "VALUE");
        public final static Property Remark = new Property(7, String.class, "remark", false, "REMARK");
        public final static Property CheckState = new Property(8, String.class, "checkState", false, "CHECK_STATE");
        public final static Property UpLoadState = new Property(9, String.class, "upLoadState", false, "UP_LOAD_STATE");
        public final static Property LineId = new Property(10, Long.class, "lineId", false, "LINE_ID");
        public final static Property AreaId = new Property(11, Long.class, "areaId", false, "AREA_ID");
        public final static Property FacilityId = new Property(12, Long.class, "facilityId", false, "FACILITY_ID");
        public final static Property InspectionId = new Property(13, Long.class, "inspectionId", false, "INSPECTION_ID");
    }

    private DaoSession daoSession;

    private Query<Record> area_RecordListQuery;
    private Query<Record> facility_RecordListQuery;
    private Query<Record> inspection_RecordListQuery;
    private Query<Record> line_RecordListQuery;

    public RecordDao(DaoConfig config) {
        super(config);
    }
    
    public RecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: mmid
                "\"ID\" INTEGER," + // 1: id
                "\"START_TIME\" TEXT," + // 2: startTime
                "\"END_TIME\" TEXT," + // 3: endTime
                "\"CHECKER\" TEXT," + // 4: checker
                "\"TYPE\" TEXT," + // 5: type
                "\"VALUE\" TEXT," + // 6: value
                "\"REMARK\" TEXT," + // 7: remark
                "\"CHECK_STATE\" TEXT," + // 8: checkState
                "\"UP_LOAD_STATE\" TEXT," + // 9: upLoadState
                "\"LINE_ID\" INTEGER," + // 10: lineId
                "\"AREA_ID\" INTEGER," + // 11: areaId
                "\"FACILITY_ID\" INTEGER," + // 12: facilityId
                "\"INSPECTION_ID\" INTEGER);"); // 13: inspectionId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Record entity) {
        stmt.clearBindings();
 
        Long mmid = entity.getMmid();
        if (mmid != null) {
            stmt.bindLong(1, mmid);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
 
        String startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindString(3, startTime);
        }
 
        String endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindString(4, endTime);
        }
 
        String checker = entity.getChecker();
        if (checker != null) {
            stmt.bindString(5, checker);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(6, type);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(7, value);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(8, remark);
        }
 
        String checkState = entity.getCheckState();
        if (checkState != null) {
            stmt.bindString(9, checkState);
        }
 
        String upLoadState = entity.getUpLoadState();
        if (upLoadState != null) {
            stmt.bindString(10, upLoadState);
        }
 
        Long lineId = entity.getLineId();
        if (lineId != null) {
            stmt.bindLong(11, lineId);
        }
 
        Long areaId = entity.getAreaId();
        if (areaId != null) {
            stmt.bindLong(12, areaId);
        }
 
        Long facilityId = entity.getFacilityId();
        if (facilityId != null) {
            stmt.bindLong(13, facilityId);
        }
 
        Long inspectionId = entity.getInspectionId();
        if (inspectionId != null) {
            stmt.bindLong(14, inspectionId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Record entity) {
        stmt.clearBindings();
 
        Long mmid = entity.getMmid();
        if (mmid != null) {
            stmt.bindLong(1, mmid);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
 
        String startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindString(3, startTime);
        }
 
        String endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindString(4, endTime);
        }
 
        String checker = entity.getChecker();
        if (checker != null) {
            stmt.bindString(5, checker);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(6, type);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(7, value);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(8, remark);
        }
 
        String checkState = entity.getCheckState();
        if (checkState != null) {
            stmt.bindString(9, checkState);
        }
 
        String upLoadState = entity.getUpLoadState();
        if (upLoadState != null) {
            stmt.bindString(10, upLoadState);
        }
 
        Long lineId = entity.getLineId();
        if (lineId != null) {
            stmt.bindLong(11, lineId);
        }
 
        Long areaId = entity.getAreaId();
        if (areaId != null) {
            stmt.bindLong(12, areaId);
        }
 
        Long facilityId = entity.getFacilityId();
        if (facilityId != null) {
            stmt.bindLong(13, facilityId);
        }
 
        Long inspectionId = entity.getInspectionId();
        if (inspectionId != null) {
            stmt.bindLong(14, inspectionId);
        }
    }

    @Override
    protected final void attachEntity(Record entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Record readEntity(Cursor cursor, int offset) {
        Record entity = new Record( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // mmid
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // startTime
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // endTime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // checker
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // type
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // value
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // remark
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // checkState
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // upLoadState
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10), // lineId
            cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11), // areaId
            cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12), // facilityId
            cursor.isNull(offset + 13) ? null : cursor.getLong(offset + 13) // inspectionId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Record entity, int offset) {
        entity.setMmid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setStartTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEndTime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setChecker(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setValue(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setRemark(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCheckState(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setUpLoadState(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setLineId(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
        entity.setAreaId(cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11));
        entity.setFacilityId(cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12));
        entity.setInspectionId(cursor.isNull(offset + 13) ? null : cursor.getLong(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Record entity, long rowId) {
        entity.setMmid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Record entity) {
        if(entity != null) {
            return entity.getMmid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Record entity) {
        return entity.getMmid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "recordList" to-many relationship of Area. */
    public List<Record> _queryArea_RecordList(Long areaId) {
        synchronized (this) {
            if (area_RecordListQuery == null) {
                QueryBuilder<Record> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AreaId.eq(null));
                area_RecordListQuery = queryBuilder.build();
            }
        }
        Query<Record> query = area_RecordListQuery.forCurrentThread();
        query.setParameter(0, areaId);
        return query.list();
    }

    /** Internal query to resolve the "recordList" to-many relationship of Facility. */
    public List<Record> _queryFacility_RecordList(Long facilityId) {
        synchronized (this) {
            if (facility_RecordListQuery == null) {
                QueryBuilder<Record> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.FacilityId.eq(null));
                facility_RecordListQuery = queryBuilder.build();
            }
        }
        Query<Record> query = facility_RecordListQuery.forCurrentThread();
        query.setParameter(0, facilityId);
        return query.list();
    }

    /** Internal query to resolve the "recordList" to-many relationship of Inspection. */
    public List<Record> _queryInspection_RecordList(Long inspectionId) {
        synchronized (this) {
            if (inspection_RecordListQuery == null) {
                QueryBuilder<Record> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.InspectionId.eq(null));
                inspection_RecordListQuery = queryBuilder.build();
            }
        }
        Query<Record> query = inspection_RecordListQuery.forCurrentThread();
        query.setParameter(0, inspectionId);
        return query.list();
    }

    /** Internal query to resolve the "recordList" to-many relationship of Line. */
    public List<Record> _queryLine_RecordList(Long lineId) {
        synchronized (this) {
            if (line_RecordListQuery == null) {
                QueryBuilder<Record> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.LineId.eq(null));
                line_RecordListQuery = queryBuilder.build();
            }
        }
        Query<Record> query = line_RecordListQuery.forCurrentThread();
        query.setParameter(0, lineId);
        return query.list();
    }

}
